### ISSUE TITLE
anyway to introduce font styles into the final style?

### ISSUE THREAD

**Issue by SkyJedi** [foisonocean/react-dynamic-font#2]
I'd like to bold the result of the dynamic font component but don't see a easy way to do that?  it's be cool to pass a prop to introduce the final style

**Comment by hronro** [comment]
You can add styles to its parent element.
For example:
```jsx
render() {
  return (
    <div>
      {/* ... */}
      <div className="my-class" styles={{fontWeight: 'bold'}}>
        <DynamicFont />
      </div>
    </div>
  );
}
```
